service: nest-serverless-fastify

useDotenv: true

plugins:
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  timeout: 600
  runtime: nodejs18.x
  environment: ${file(ymls/environment.yml)}

functions: ${file(ymls/functions.yml)}
